### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by morbidick** [morbidick/git.express#1]
* [ ] boilerplate with gin-gonic and reform
* [ ] implement oauth login with github
* [ ]  fetch issue list from github
* [ ] implement oauth for gitlab and linking accounts
* [ ]  show combined issue list
* [ ]  add self hosted gitlab instances
* [ ]  combined project list
* [ ]  combined pr list
* [ ]  creating user profiles 
  * [ ]  define one of your linked account as primary
  * [ ]  url idea git.express/github.com/morbidick (other url forward to the primary url)
* [ ]  move backend to a rest only interface and build fancy frontend with p3 and lit-html
